--- #YAML:1.0
name:                forks-BerkeleyDB
version:             0.054
abstract:            High performance drop-in replacement for threads
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    BerkeleyDB:                    0.27
    Devel::Required:               0.07
    forks:                         0.23
    Storable:                      0
    Tie::Restore:                  0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Eric Rybski (rybskej@yahoo.com)
